version: '3'
services:
  app_container:
    image : my_app:1.0
    ports : 
      -8080:8080
    environment : 
      -USERNAME=admin
      -PASSWORD=password
  db_container:
    image : mysql
    ports :
      -3306:3306
    environment :
      -MYSQL_ROOT_PASSWORD=my-secret-pw
     
